version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/web-ui
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
