# syntax=docker/dockerfile:1

FROM sbtscala/scala-sbt:eclipse-temurin-21.0.8_9_1.12.6_3.8.2 AS build

WORKDIR /build

COPY project/ project/
COPY build.sbt ./
COPY apps/ apps/
COPY modules/ modules/

RUN sbt "lichessBridgeService / stage"

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /build/apps/lichess-bridge-service/target/universal/stage/ ./

ENV LICHESS_BRIDGE_HTTP_HOST=0.0.0.0 \
    LICHESS_BRIDGE_HTTP_PORT=8090 \
    LICHESS_BRIDGE_ENABLED=false \
    LICHESS_API_BASE_URL=https://lichess.org \
    AI_SERVICE_URL=http://ai-service:8765

CMD ["bin/searchess-lichess-bridge-service"]
