# syntax=docker/dockerfile:1

FROM sbtscala/scala-sbt:eclipse-temurin-21.0.8_9_1.12.6_3.8.2 AS build

WORKDIR /build

COPY project/ project/
COPY build.sbt ./
COPY apps/ apps/
COPY modules/ modules/

RUN sbt "lichessBot / stage"

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /build/apps/lichess-bot/target/universal/stage/ ./

ENV GAME_SERVICE_BASE_URL=http://game-service:8080 \
    EXTERNAL_GAME_BOT_PLATFORM=Lichess \
    EXTERNAL_GAME_BOT_ACTOR_ID=selinasa

CMD ["bin/searchess-lichess-bot"]
