apiVersion: v1
kind: ConfigMap
metadata:
  name: lichess-bot-env
  namespace: searchess
data:
  GAME_SERVICE_BASE_URL: "http://game-service:8080"
  EXTERNAL_GAME_BOT_PLATFORM: "Lichess"
  EXTERNAL_GAME_BOT_ACTOR_ID: "arutepsu"
