apiVersion: v1
kind: Service
metadata:
  name: lichess-bot
  namespace: searchess
  labels:
    app: lichess-bot
spec:
  type: ClusterIP
  selector:
    app: lichess-bot
  ports:
    - name: challenge
      port: 9324
      targetPort: challenge
