apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: searchess
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8765
      targetPort: http
