apiVersion: v1
kind: Service
metadata:
  name: python-ai-service
  namespace: searchess
  labels:
    app: python-ai-service
spec:
  selector:
    app: python-ai-service
  ports:
    - name: http
      port: 8765
      targetPort: http
