apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: searchess
  labels:
    app: history-service
spec:
  type: ClusterIP
  selector:
    app: history-service
  ports:
    - name: http
      port: 8081
      targetPort: http
