apiVersion: v1
kind: Service
metadata:
  name: lichess-bridge-service
  namespace: searchess
  labels:
    app: lichess-bridge-service
spec:
  type: ClusterIP
  selector:
    app: lichess-bridge-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
