addSbtPlugin("org.scoverage"   %  "sbt-scoverage"       % "2.0.11")
addSbtPlugin("org.scoverage"   %  "sbt-coveralls"       % "1.3.1")
addSbtPlugin("com.github.sbt"  %  "sbt-native-packager" % "1.10.4")
addSbtPlugin("org.scalameta"   %  "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.5.6")
