apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: searchess
  labels:
    app: mongo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
