package chess.application.session.model

/** Represents who or what controls one side of the board.
 *
 *  This is a pure application-layer concept: it governs how move input is
 *  sourced for a color, not how moves are validated.  Chess rules remain
 *  entirely in the domain layer regardless of who supplies the moves.
 *
 *  - [[HumanLocal]]: input comes from a local UI (keyboard, mouse, touch).
 *  - [[HumanRemote]]: input comes from a remote player over a network connection.
 *    The connection detail is managed outside this model.
 *  - [[AI]]: input is generated by an AI engine.  The optional `engineId`
 *    names the engine/strategy (e.g. "stockfish-15", "random", "minimax-depth3").
 *    When absent, the session service selects the default engine.
 *
 *  `engineId` is intentionally `Option[String]` rather than a typed enum so
 *  that new engines can be registered without a model change.  A typed
 *  `EngineDescriptor` ADT can replace it in Phase 3 if engine capability
 *  negotiation is required.
 */
enum SideController:
  case HumanLocal
  case HumanRemote
  case AI(engineId: Option[String] = None)
