apiVersion: v1
kind: Service
metadata:
  name: tournament-service
  namespace: searchess
  labels:
    app: tournament-service
spec:
  type: ClusterIP
  selector:
    app: tournament-service
  ports:
    - name: http
      port: 8085
      targetPort: http
